export const GET_LOTR_CHARATERS_REQUEST = 'GET_LOTR_CHARATERS_REQUEST';
export const GET_LOTR_CHARATERS_SUCCESS = 'GET_LOTR_CHARATERS_SUCCESS';
export const GET_LOTR_CHARATERS_ERROR = 'GET_LOTR_CHARATERS_ERROR';
